package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TemplatePropertiesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplatePropertiesAllPropertiesEquals(TemplateProperties expected, TemplateProperties actual) {
        assertTemplatePropertiesAutoGeneratedPropertiesEquals(expected, actual);
        assertTemplatePropertiesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplatePropertiesAllUpdatablePropertiesEquals(TemplateProperties expected, TemplateProperties actual) {
        assertTemplatePropertiesUpdatableFieldsEquals(expected, actual);
        assertTemplatePropertiesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplatePropertiesAutoGeneratedPropertiesEquals(TemplateProperties expected, TemplateProperties actual) {
        assertThat(actual)
            .as("Verify TemplateProperties auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplatePropertiesUpdatableFieldsEquals(TemplateProperties expected, TemplateProperties actual) {
        assertThat(actual)
            .as("Verify TemplateProperties relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplatePropertiesUpdatableRelationshipsEquals(TemplateProperties expected, TemplateProperties actual) {
        assertThat(actual)
            .as("Verify TemplateProperties relationships")
            .satisfies(a -> assertThat(a.getTemplateColumn()).as("check templateColumn").isEqualTo(expected.getTemplateColumn()));
    }
}
